[package]
authors     = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage data struct"
edition     = "2021"
license     = "MIT"
name        = "istanbul-oxide"
repository  = "https://github.com/kwonoj/swc-coverage-instrument"
version     = "0.0.20"

[dependencies]
indexmap = { workspace = true, features = ["serde"] }
serde    = { workspace = true, features = ["derive"] }
